# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.position import Position
from openapi_server import util

from openapi_server.models.position import Position  # noqa: E501

class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: Position
        """
        self.openapi_types = {
            'data': Position
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: Position
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: Position
        """

        self._data = data
