version: '3'

services:
  mockapp:
    build:
      context: ./mockapp
    ports:
      - 8081:8080
    networks:
      - dolorlectum
  lamp:
    build:
      context: ./lamp
    ports:
      - 8084:8085
    networks:
      - dolorlectum
  collector:
    build:
      context: ./collector
    depends_on:
      - "mqtt-server"
    networks:
      - dolorlectum

  mqtt-server:
    image: eclipse-mosquitto
    ports:
      - 9883:1883
      - 10001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - dolorlectum

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  dolorlectum: