version: '3'

services:
  mattress_vacuum:
    build:
      context: ./mattress_vacuum
    ports:
      - 8081:8080
    networks:
      - dolorlectum
    depends_on:
      - "mqtt-server"

  thermalsystem:
    build:
      context: ./thermalsystem
    ports:
      - 8082:8080
    networks:
      - dolorlectum
    depends_on:
      - "mqtt-server"


  soundsystem:
    build:
      context: ./soundsystem
    ports:
      - 8083:8080
    networks:
      - dolorlectum
    depends_on:
      - "mqtt-server"

  lamp:
    build:
      context: ./lamp
    ports:
      - 8084:8080
    networks:
      - dolorlectum
    depends_on:
      - "mqtt-server"

  tv-movement:
    build:
      context: ./tv-movement
    ports:
      - 8085:8080
    networks:
      - dolorlectum
    depends_on:
      - "mqtt-server"

  collector:
    build:
      context: ./collector
    depends_on:
      - "mqtt-server"
    networks:
      - dolorlectum

  mqtt-server:
    image: eclipse-mosquitto
    ports:
      - 9883:1883
      - 10001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - dolorlectum
      
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    networks:
      - dolorlectum
    depends_on:
      - tv-movement
      - lamp
      - soundsystem
      - thermalsystem
      - mattress_vacuum

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  dolorlectum:
