/*
 * mockapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"mockapp/httpapi"
)

func main() {
	log.Printf("Server started")

	router := httpapi.NewRouter()

	log.Fatal(router.Run(":8080"))
}
