openapi: 3.0.0
info:
  description: The system that regulates the heat of the matress
  title: Thermal System
  version: 1.0.1
externalDocs:
  description: Find out more about DolorLectum
  url: https://github.com/JustBeYou/DolorLectum
servers:
- url: /
paths:
  /status:
    get:
      operationId: get_thermal_status
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: Get the status
      summary: Get the status
      tags:
      - Status
      x-openapi-router-controller: openapi_server.controllers.status_controller
    post:
      operationId: set_thermal_status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
      responses:
        "200":
          description: Status set successful
      summary: Set status
      tags:
      - Status
      x-openapi-router-controller: openapi_server.controllers.status_controller
  /temp:
    post:
      operationId: set_temperature
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'  
      responses:
        "200":
          description: Temp set successful
      summary: Set the temperature
      tags:
      - Status
      x-openapi-router-controller: openapi_server.controllers.status_controller
  
  
  /action:
    post:
      operationId: work
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
          description: The action that regulates the thermal system
      summary: Action upon the thermal system
      tags:
      - Action
      x-openapi-router-controller: openapi_server.controllers.action_controller
components:
  schemas:
    Status:
      example:
        ready: true
      properties:
        ready:
          title: ready
          type: boolean
        temp:
          title: temp
          type: number
        realtemp:
          title: realtemp
          type: number
      title: Status
      type: object
    Action:
      example:
        action: cancel
      properties:
        action:
          enum:
          - work
          - cancel
          title: action
          type: string
      title: Action
      type: object
